### ISSUE TITLE
Caldera Forms 1.5 - Entry Export/View/Edit results in 500 error

### ISSUE THREAD

**Issue by charliethetuna** [CalderaWP/Caldera-Forms#1268]
Any time I try to export a forms entries, or view/edit a single entry it results in a 500 error. 

Here is the error message reported:
PHP Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in {WP_PATH}/wp-content/plugins/caldera-forms/classes/magic.php on line 44 and defined in {WP_PATH}/wp-content/plugins/caldera-forms/classes/field/util.php on line 348, referer: {WP_SITE}/wp-admin/admin.php?page=caldera-forms

WordPress Version: 4.7.2
PHP Version: 5.5.22
MySQL Version: 5.5.52
Caldera Forms Version: 1.5.0
WP_DEBUG:

**Comment by Shelob9** [comment]
Thank you for using Caldera Forms and for these details. I will get this fixed in 1.5.0.1

**Comment by Shelob9** [comment]
I could not reproduce this, must be an add on calling it wrong, probably indirectly. So I put in a check to fix $form being empty using global.

**Comment by Shelob9** [comment]
Close via 	6af31c0
@charliethetuna I'm going to push this out with 1.5.0.1 If you still see the issue after the update, please reopen the issue and tell me which add-ons you have and which processors are in the form that causes this error.

**Comment by charliethetuna** [comment]
@Shelob9 I just updated to 1.5.0.3 and this error is still present. I did notice that is only happening on one of the forms on the site, the others are all able to export fine. The odd thing is they all use the same field types. PHP error reported is exactly the same as before.

**Comment by kaioe** [comment]
This still happening with me, using PHP 5.6 and all plugins disabled.

**Comment by charls637** [comment]
Having this issue:
Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /nas/content/staging/firstvotenc/wp-content/plugins/caldera-forms/classes/magic.php on line 44 and defined in /nas/content/staging/firstvotenc/wp-content/plugins/caldera-forms/classes/field/util.php on line 361

after resending the mail to a client, i got 2 forms and they have the same issue

**Comment by TheGiops** [comment]
New installation of WordPress.
As soon as I activated Caldera Forms, the whole website went into an Error 500, no longer able to access either Admin or site.
